'use client'
import Head from 'next/head'
// import { useTheme } from '@emotion/react'
// import { useSettings } from 'src/hooks/useSettings';
import CustomTextField from 'src/components/text-field';
import { Box } from '@mui/material';

export default function Home() {
  // const theme = useTheme()
  // const {settings} = useSettings()
  // console.log('theme', {theme, settings})

  return (
    <>
      <Head>
        <title>Store shop</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ margin: 6, width: "200px" }}>
        <CustomTextField id='outlined-multiline-flexible' label='Multiline' />
      </Box>
    </>
  )
}
