import styles from '../page.module.css'

export const generateMetadata = () => {
  return {
    title: "Phong pro",
    description: "Generated by create next app with Phong pro",
  }
}

export default function Blog() {
  return (
    <main className={styles.main}>
        Blog Page
    </main>
  );
}
