name: Deploy Backend to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BE_PROJECT_ID }} # Dùng Project ID riêng cho BE

on:
  push:
    branches:
      - main
      - master
    paths:
      - "Proj_2/API_SHOP/**" # Đổi đường dẫn này thành thư mục chứa BE của bạn
  workflow_dispatch:

jobs:
  Deploy-BE-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_BE_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_BE_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_BE_TOKEN }}
